theme:
  - osuny
  - osuny-plugin-centered-footer
_merge: deep
params:
  summary:
    position: content
  breadcrumb:
    position: after-hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/logo.png'
  home:
    head:
      title: site
  categories:
    single:
      taxonomies:
        display: true
  organizations:
    single:
      backlinks: true
  projects:
    default_image: true
    index:
      layout: grid
      options:
        categories: false
        image: true
        subtitle: true
        summary: true
        year: false
    single:
      meta:
        position: hero
        options:
          authors: false
          dates: false
          year: false
          published_at: true
          reading_time: false
          share: false
          taxonomies: true
          updated_at: false
          with_labels: true
