[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/agenda/etat/residence-1/index.html"
to = "/agenda/etat/residence/"

[[redirects]]
from = "/agenda/etat/diffusion-1/index.html"
to = "/agenda/etat/diffusion/"

[[redirects]]
from = "/agenda/etat/premiere-1/index.html"
to = "/agenda/etat/premiere/"

